### ISSUE TITLE
Api Error 

### ISSUE THREAD

**Issue by dav478923** [godaddy/docker-machine-godaddy#4]
Hi !

While trying to create a docker test machine I got the following error 
Error creating machine: Error in driver during machine creation: {"code":"MALFORMED_CREDENTIALS","message":"Credentials are malformed","name":"ApiError"} 
Any idea of what cause this error ?
I appreciate your help .

**Comment by aka-bo** [comment]
This error usually indicates a missing or invalid GoDaddy API key. When executing `docker-machine create --driver godaddy` be sure to provide your API key (https://developer.godaddy.com/keys) via the `--godaddy-api-key` flag (or exported `GODADDY_API_KEY` env variable). 

Note that the API key you provide must include both the “key” and “secret” separated by a colon, e.g. `--godaddy-api-key ${YOUR_KEY}:${YOUR_SECRET}`
The “secret” portion of the key is only displayed during key creation, you can create a new key if you no longer have this info.

If you continue to experience issues the `--debug` flag can be used to output additional information. If you like, you can reply with the output of the `docker-machine create` command and I’ll help if I can.
